name = "server-defender"
repo = "https://github.com/ptrel1/server-defender.git"
deploy_type = "python-git"
supervisor_service = "server-defender"
deploy_user = "root"

[go_single]
  binary = ""

[python_git]
  manifest_file = "file_manifest.json"

[deploy]
  command = "venv/bin/python app.py"
  user = "root"
  log_file = "/main/log/app/server-defender.log"
