[program:server-defender]
command = /main/app/github/server-defender/venv/bin/python /main/app/github/server-defender/app.py
directory = /main/app/github/server-defender
autostart = true
autorestart = true
startretries = 1000000
startsecs = 5
user = root
stdout_logfile = /main/app/log/server-defender.log
stdout_logfile_maxbytes = 1MB
stdout_logfile_backups = 0
redirect_stderr = true
